### ISSUE TITLE
toko voip crahsing teamspek

### ISSUE THREAD

**Issue by alficondo** [Itokoyamato/TokoVOIP_TS3#100]
when installed it will not open teamspeak it will only come up with this crashlog 

Sent: 16384/61611 bytes
Sent: 61611/61611 bytes
Error: 201
AccessDeniedInvalid according to Policy: Policy expired.D8635E14DBB0E20DheJhKidJ67fp+e9u3AofXvpFAvDdU39i40ABwhq5Q+ibIgYgXtMNB5xX56RV5FTfshCwxeRKRJs=

**Comment by Itokoyamato** [comment]
Thats not a crashlog, it's just teamspeak sending crash data.
Tokovoip 1.5.0 has been [released](https://github.com/itokoyamato/tokovoip_ts3/releases) and should be more stable
Please try again once your server is updated to tokovoip 1.5.0. (don't update your teamspeak plugin until the server you play on updates as well)
Feel free to open a new issue if the problem persists on the latest versions.
