### ISSUE TITLE
Radio Key Problm

### ISSUE THREAD

**Issue by zoomlordir** [Itokoyamato/TokoVOIP_TS3#103]
when Someone In TeamSpeak Use Radio with Radio Key He Can't Talk in Normal Voice and how can i change the position of toko voip hud [tokovoip] Normal or Radio

**Comment by Itokoyamato** [comment]
Tokovoip 1.5.0 has been [released](https://github.com/itokoyamato/tokovoip_ts3/releases) and has improvements to the voice activation system
Please try again once your server is updated to tokovoip 1.5.0. (don't update your teamspeak plugin until the server you play on updates as well)
Feel free to open a new issue if the problem persists on the latest versions.
