### ISSUE TITLE
Onesync Infinity problem

### ISSUE THREAD

**Issue by JakinGZ** [Itokoyamato/TokoVOIP_TS3#104]
When you are away from the person who is on the radio with you, they do not hear you and you do not hear them and out of nowhere you start to hear several players.

**Comment by Poggicek** [comment]
Tokovoip doesn't support infinity yet

**Comment by thiagotxd** [comment]
and how have servers running with tokovoip infinity?

**Comment by Poggicek** [comment]
It's called "Knowing how to code or look into pr's"

**Comment by Itokoyamato** [comment]
Tokovoip 1.5.0 has been [released](https://github.com/itokoyamato/tokovoip_ts3/releases) and has full support for onesync infinity.
Please try again once your server is updated to tokovoip 1.5.0. (don't update your teamspeak plugin until the server you play on updates as well)
Feel free to open a new issue if the problem persists on the latest versions.
