### ISSUE TITLE
Radio animation

### ISSUE THREAD

**Issue by maguhd** [Itokoyamato/TokoVOIP_TS3#106]
Radio animation works only in some channels, Like 2-3-4. Is there any way to use the radio animation on all the channels?

**Comment by maguhd** [comment]
I fixed it, replacing line 138 to 172 with:



```			if (IsControlPressed(0, self.radioKey) and self.plugin_data.radioChannel ~= -1) then -- Talk on radio
				self.plugin_data.radioTalking = true;
				self.plugin_data.localRadioClicks = true;
				if (self.plugin_data.radioChannel > 100) then
					self.plugin_data.localRadioClicks = false;
				end
				if (not getPlayerData(self.serverId, "radio:talking")) then
					setPlayerData(self.serverId, "radio:talking", true, true);
				end
				self:updateTokoVoipInfo();
				if (lastTalkState == false and self.myChannels[self.plugin_data.radioChannel]) then
					if true then --(not string.match(self.myChannels[self.plugin_data.radioChannel].name, "Call") and not IsPedSittingInAnyVehicle(PlayerPedId())) then
						if self.plugin_data.radioChannel ~= -1 and self.plugin_data.radioChannel < 100 then
							RequestAnimDict("random@arrests");
							while not HasAnimDictLoaded("random@arrests") do
								Wait(5);
							end
							print(self.plugin_data.radioChannel)
							TaskPlayAnim(PlayerPedId(),"random@arrests","generic_radio_chatter", 8.0, 0.0, -1, 49, 0, 0, 0, 0);
						end
					end
					lastTalkState = true
				end
			else
				self.plugin_data.radioTalking = false;
				if (getPlayerData(self.serverId, "radio:talking")) then
					setPlayerData(self.serverId, "radio:talking", false, true);
				end
				self:updateTokoVoipInfo();
				
				if lastTalkState == true then
					lastTalkState = false
					StopAnimTask(PlayerPedId(), "random@arrests","generic_radio_chatter", -4.0);
				end
			end
		end
	end);
end```

**Comment by Itokoyamato** [comment]
It is intended for radio animations to work only on pre-configured radio channels

**Comment by TubeN86** [comment]
> 
> 
> I fixed it, replacing line 138 to 172 in c_TokoVoip.lua
> with:
> 
> ```lua
> 			if (IsControlPressed(0, self.radioKey) and self.plugin_data.radioChannel ~= -1) then -- Talk on radio
> 				self.plugin_data.radioTalking = true;
> 				self.plugin_data.localRadioClicks = true;
> 				if (self.plugin_data.radioChannel > 100) then
> 					self.plugin_data.localRadioClicks = false;
> 				end
> 				if (not getPlayerData(self.serverId, "radio:talking")) then
> 					setPlayerData(self.serverId, "radio:talking", true, true);
> 				end
> 				self:updateTokoVoipInfo();
> 				if (lastTalkState == false and self.myChannels[self.plugin_data.radioChannel]) then
> 					if true then --(not string.match(self.myChannels[self.plugin_data.radioChannel].name, "Call") and not IsPedSittingInAnyVehicle(PlayerPedId())) then
> 						if self.plugin_data.radioChannel ~= -1 and self.plugin_data.radioChannel < 100 then
> 							RequestAnimDict("random@arrests");
> 							while not HasAnimDictLoaded("random@arrests") do
> 								Wait(5);
> 							end
> 							print(self.plugin_data.radioChannel)
> 							TaskPlayAnim(PlayerPedId(),"random@arrests","generic_radio_chatter", 8.0, 0.0, -1, 49, 0, 0, 0, 0);
> 						end
> 					end
> 					lastTalkState = true
> 				end
> 			else
> 				self.plugin_data.radioTalking = false;
> 				if (getPlayerData(self.serverId, "radio:talking")) then
> 					setPlayerData(self.serverId, "radio:talking", false, true);
> 				end
> 				self:updateTokoVoipInfo();
> 				
> 				if lastTalkState == true then
> 					lastTalkState = false
> 					StopAnimTask(PlayerPedId(), "random@arrests","generic_radio_chatter", -4.0);
> 				end
> 			end
> 		end
> 	end);
> end
> ```

Hey! Nice work! Any idea why i cant use my radio from my inventory after implementing this fix?

**Comment by maguhd** [comment]
this is old code. toko updated very much since then.
