### ISSUE TITLE
when I join a server which has 50-60 players my tokovoip plugin status shows offline and i am not able to talk with other players

### ISSUE THREAD

**Issue by Bhavesh02** [Itokoyamato/TokoVOIP_TS3#109]
![Desktop Screenshot 2020 05 22 - 10 59 51 39](https://user-images.githubusercontent.com/65753818/82635488-e9e05800-9c1d-11ea-9a75-76295b759ffe.png)

**Comment by Itokoyamato** [comment]
Tokovoip 1.5.0 has been [released](https://github.com/itokoyamato/tokovoip_ts3/releases) and has full support for onesync infinity.
Please try again once your server is updated to tokovoip 1.5.0. (don't update your teamspeak plugin until the server you play on updates as well)
Feel free to open a new issue if the problem persists on the latest versions.
