### ISSUE TITLE
mute/unmute all players in my channel

### ISSUE THREAD

**Issue by Thodde26** [Itokoyamato/TokoVOIP_TS3#111]
Teamspeak 3 mute/unmute all players in my channel, 
what is wrong i have a clean install and only tokovoip plugin.

https://i.imgur.com/9lK0EH3.gifv

![9lK0EH3](https://user-images.githubusercontent.com/2639719/82818734-70f03300-9e9f-11ea-9e85-83d36205718d.gif)

Best regrades  
Thodde26

**Comment by Itokoyamato** [comment]
Tokovoip 1.5.0 has been [released](https://github.com/itokoyamato/tokovoip_ts3/releases)
It includes some changes to how the mute/unmute is done, which should fix your problems
Please try again once your server is updated to tokovoip 1.5.0. (don't update your teamspeak plugin until the server you play on updates as well)
Feel free to open a new issue if the problem persists on the latest versions.
