### ISSUE TITLE
OneSync Infinity : Everyone hears everyone

### ISSUE THREAD

**Issue by Livvux** [Itokoyamato/TokoVOIP_TS3#112]
Hi, was this issue fixed?
If yes, could u please compile the tsplugin again and upload it as release? I'd be thankful since I dont get it to work.

**Comment by promraungdet** [comment]
I haven't tested
[tokovoip_1_2_5(Onesync%20Infinity).ts3_plugin](https://github.com/promraungdet/TokoVOIP_TS3_Onesync_Infinity/blob/master/tokovoip_1_2_5(Onesync%20Infinity).ts3_plugin)

**Comment by Itokoyamato** [comment]
Tokovoip 1.5.0 has been [released](https://github.com/itokoyamato/tokovoip_ts3/releases) and has full support for onesync infinity.
Please try again once your server is updated to tokovoip 1.5.0. (don't update your teamspeak plugin until the server you play on updates as well)
Feel free to open a new issue if the problem persists on the latest versions.
