### ISSUE TITLE
Toko Voip Plugin OFF ? 

### ISSUE THREAD

**Issue by guizafa** [Itokoyamato/TokoVOIP_TS3#114]
Toko voip plugin if off-line just for me ?

**Comment by zentroxx** [comment]
nope, for us too.

**Comment by ohhnice** [comment]
same issue, for pub and dev server

**Comment by ohhnice** [comment]
we tried to debug the issue on our servers, i guess FIVEM did something

**Comment by KUJHFKH** [comment]
With us Toko **Down** on all servers **Fivem** must have been wrong please solve quickly thanks

**Comment by ohhnice** [comment]
its working again

**Comment by guizafa** [comment]
Eahh its working

**Comment by KUJHFKH** [comment]
Thanks for the quick fix

**Comment by Itokoyamato** [comment]
It was blacklisted again by fivem, but they rollbacked quickly after. A long term solution is being worked on.
