### ISSUE TITLE
attempt to compare boolean with number

### ISSUE THREAD

**Issue by humaniti** [Itokoyamato/TokoVOIP_TS3#116]
Hello!

So we have configured TokoVoip on our Onesync 128 Slot server, everything works fine only premade job radios. For example, we made 2 radio channels on (2 and 3 Mhz) for Ambulance, if they join, they get this issue:

SCRIPT ERROR: tokovoip_script/src/c_main.lua:155: attemt to compare boolean with number
https://imgur.com/MGUFdsL

Any ideas whats going wrong?

Thanks!

**Comment by Deniel00** [comment]
There:
https://github.com/Itokoyamato/TokoVOIP_TS3/blob/master/fivem_script/tokovoip_script/src/c_main.lua#L155
Change to:
`if (type(remotePlayerChannel) == "number" and remotePlayerChannel <= voip.config.radioClickMaxChannel) then`

**Comment by Itokoyamato** [comment]
The fix has been added in the upcoming update (#126)
