### ISSUE TITLE
Tokovoip Error after many players

### ISSUE THREAD

**Issue by Ards1719** [Itokoyamato/TokoVOIP_TS3#119]
Tokovoip error after 40 more players, so it looks like player A came to me, i cant hear him. while player B from the beginning with me before error, when he was far from me, but his voice was still heard. how to fixed it? i already uninstall fivem, tokovoip, teamspeak,and clear cache.

**Comment by Itokoyamato** [comment]
Tokovoip 1.5.0 has been [released](https://github.com/itokoyamato/tokovoip_ts3/releases) and has full support for onesync infinity.
Please try again once your server is updated to tokovoip 1.5.0. (don't update your teamspeak plugin until the server you play on updates as well)
Feel free to open a new issue if the problem persists on the latest versions.
