### ISSUE TITLE
TokoVOIP ws_server 

### ISSUE THREAD

**Issue by Danio112PL** [Itokoyamato/TokoVOIP_TS3#121]
Mam pytanie gdzie mam znaleźć websocket server czyli "ip:port" skoro IP mojego serwera FiveM nie działa i cały tokovoip nie działa.

**Comment by Poggicek** [comment]
Could you please talk english?

**Comment by Danio112PL** [comment]
I have a question where to find the WWW server, ie "ip: port" since the IP of my FiveM server does not work and all tokovoip does not work.

**Comment by Danio112PL** [comment]
sorry for the mistakes but I use a translator

**Comment by Danio112PL** [comment]
sorry for the mistakes but I use a translator

**Comment by Danio112PL** [comment]
sorry for the mistakes but I use a translator

**Comment by Itokoyamato** [comment]
Please check the upcoming PR #116 as it makes the setup a lot more easy
