### ISSUE TITLE
Plugin problem

### ISSUE THREAD

**Issue by Jotteri77** [Itokoyamato/TokoVOIP_TS3#123]
I have a problem with newest plugin (1.5.0) and script (1.5.0) when i join server and open teamspeak i got "Tokovoip offline" any ideas? Edit: And i have plugin Enabled

**Comment by Duqino** [comment]
i got the same problem. Still trying to figure it out.

**Comment by Itokoyamato** [comment]
1.5.0 requires the ws-server. Did you set it up ?

**Comment by Jotteri77** [comment]
^^ Yes i setted up

**Comment by Itokoyamato** [comment]
What does your configs look like ? You need to edit ws_server/config.js and tokovoip_script/c_config.lua

**Comment by Jotteri77** [comment]
Yes i editted i can send teamspeak client log if you need

**Comment by wutthipong-luangsanam** [comment]
i have same problem

**Comment by Duqino** [comment]
I just setup ws_server and its running. I used 3000 as port and add my IP in the tokovoip config and the ws_server config. But still nothing.
