### ISSUE TITLE
Can't seem to figure out the Websocket Server

### ISSUE THREAD

**Issue by JustSafety** [Itokoyamato/TokoVOIP_TS3#127]
Hey everyone,

Can someone maybe help me with setting up the WS server?
Can't seem to figure it out unfornately.

**Comment by Itokoyamato** [comment]
Please check the upcoming PR #126 as it makes the setup a lot easier

**Comment by JustSafety** [comment]
> Please check the upcoming PR #126 as it makes the setup a lot easier
> Otherwise, feel free to join the discord and ask for support there. It'll be faster to help you

Thanks, it's the first time for me setting something up like this. I can't find your Discord server could you pass me the link?

**Comment by Itokoyamato** [comment]
Sure, there you go:
https://discord.gg/nbEprAw
