### ISSUE TITLE
Config option for TeamSpeak port

### ISSUE THREAD

**Issue by JasmineMassii** [Itokoyamato/TokoVOIP_TS3#135]
One of the problems I had when I (attempted to) install 1.5.1 was that the TeamSpeak port defaulted to a pre-defined port (not familier enough with TS to know if it's the port used on server install by default). However, the service I use defines its individual servers by port number (in my case, 9408).
I was walked through changing it by Neddings. Changing it in itself is not difficult, but for a newer user (and for those still learning, like me! :D), having to dig through the coding looking for the ports to change, it can be a daunting prospect.

I think adding a "TeamspeakPort" to the config would be useful for those who have their servers on ports other than the defaults, either by choice or not.

**Comment by Itokoyamato** [comment]
The teamspeak port is not used for anything. I added a warning that checks for the TS server, but it's almost always triggered. Probably going to remove the check.

**Comment by nation-games** [comment]
i have the same problem, how can I use a custom port?

**Comment by mendigor** [comment]
same, how do I create custom port?

**Comment by claudio341** [comment]
I have the same problem, how can I use a custom port?

**Comment by RodneyMO95** [comment]
I have the same problem, how can I use a custom port?

**Comment by Itokoyamato** [comment]
I will repeat since it doesn't appear to be clear enough: teamspeak port is not necessary, it is not used for any checks or system. It does not matter, it only needs the ip for a quick check.
The ws-server warning has been removed.
