### ISSUE TITLE
OFFLINE TOKOVOIP

### ISSUE THREAD

**Issue by xScriptedx** [Itokoyamato/TokoVOIP_TS3#136]
I currently have everything perfectly setup but it says OFFLINE for all players. I've been struggling for 6 hours to fix this issue please someone assist me. No console errors. I'm curious what this new ws_server ip:port thing is?

Thanks,
Calvin

**Comment by xScriptedx** [comment]
Fixed it :) Nvm

**Comment by DidrikxD** [comment]
How did you fix it? :)

**Comment by draobrehtom** [comment]
@xScriptedx I am also wondering about it, could you please share your idea?

**Comment by FancyBean** [comment]
I'm also wondering how you fixed it :)

**Comment by xScriptedx** [comment]
@FancyBean 
@draobrehtom 
@DidrikxD 

Basically, TokoVOIP has new installation method. You must ensure you called installed the ws_server correctly in coherence with your tokovoip_script. After all that, you should be good. Let me know if you have any other issues I'll be willing to help. The owner needs some time off once in a while ⭕ 

Best regards,
Calvin

**Comment by Itokoyamato** [comment]
Tokovoip 1.5.0 is not backward compatible with 1.2.5. Make sure both servers and clients are using the same versions.

Glad you figured it out on your own @xScriptedx
