### ISSUE TITLE
Splitting FiveM&Ts3 networks ,VPN

### ISSUE THREAD

**Issue by YsaHZ** [Itokoyamato/TokoVOIP_TS3#137]
for one of the teamspeak servers i have to use vpn all the time before i had my vpn only Filter Teamspeak so i could connect there but since the new version i have to tunnel my whole computer or at least teamspeak and fiveM should use the same network for it to work otherwise it says TokoVOIP Offline. i wish there was a solution cuz i don't wanna have a high ping on game server because of a vpn! i only want to use vpn on ts3.

**Comment by Itokoyamato** [comment]
Unfortunately, the only identifies I can use to handshake is your IP address. They have to match between fivem and ts3
