### ISSUE TITLE
Server wont recognize that I'm using the correct plugin version

### ISSUE THREAD

**Issue by Jbn1127** [Itokoyamato/TokoVOIP_TS3#150]
![Annotation 2020-07-12 160917](https://user-images.githubusercontent.com/68243077/87332026-f049cc80-c508-11ea-8409-7c9d7307cef8.png)
![Annotation 2020-07-12 161246](https://user-images.githubusercontent.com/68243077/87332027-f0e26300-c508-11ea-9079-c3ee12c81cdd.png)

due to an update to require the 1.5.2 version of tokovoip, When i try to join the server it wont recognize that im using the correct version. i have uninstalled and reinstalled both tokovoip and ts3 multiple times. I managed to get it to work once yesterday, but when i tried to join today i had the same issue, and what i did to fix it yesterday is no longer working.

**Comment by Robijntjee** [comment]
How did you fix this? It would be nice if you say how you fixed it before you close the issue..

**Comment by xDope7137** [comment]
Disconnect and connect back in.
