### ISSUE TITLE
Plugin not Detected?

### ISSUE THREAD

**Issue by chrisrogersukgb** [Itokoyamato/TokoVOIP_TS3#151]
Hey im getting an issue where the game does not seem to be detecting the plugin, i can confirm the game is connecting to the WS Server as i can see it with the logging, however im not receiving a ts3 connection attempt, i have reinstalled TS3, reinstall TOKOVoip 1.5.2, Reinstalled both scripts on the server and am now even currently running the WS Server as standalone,

![img](https://screenshots.chrisrogersuk-ttv.co.uk/2020/07/13/1a8rlc.png)
![img](https://screenshots.chrisrogersuk-ttv.co.uk/2020/07/13/fvtxuv.png)
![img](https://screenshots.chrisrogersuk-ttv.co.uk/2020/07/13/peenis.png)

ive also left TS shut down until the black screen, restarted TS when on black screen, attempted to "Connect" in the plugin menu which after i do it is grayed out permentely until i "Disconnect"
![img](https://screenshots.chrisrogersuk-ttv.co.uk/2020/07/13/esgpvc.png)

**Comment by avilchiis** [comment]
I'm having the same issue, did u find any solution?

**Comment by LtDoc** [comment]
+1 on this. I am stuck on the same screen and it seems to only be happening for me. Other players are able to connect normally. I have done all the troubleshooting outside of resetting my PC which isn't going to happen. It was working fine 2 days ago.

**Comment by TryDmt11** [comment]
Same anyone find a fix ? I've also tried everything

**Comment by LtDoc** [comment]
> Same anyone find a fix ? I've also tried everything

I was able to get by this by deleting my FiveM cache located at C:\Users\RCMP_Desktop23\AppData\Local\FiveM\FiveM.app\cache
