### ISSUE TITLE
FiveM controller issues

### ISSUE THREAD

**Issue by Princejay21** [Itokoyamato/TokoVOIP_TS3#157]
ever since updating to the 1.5.2 version my push to talk is now on my sprint button on the controller

**Comment by DevRain2500** [comment]
Check your TS PTT key. The default key for radio/phone PTT is `Caps Lock` which is bound to sprinting. You can adjust your GTA keybind settings to adjust for this. Alternatively, you can change the keybind in the TokoVOIP config.

**Comment by Princejay21** [comment]
Hey yeah it doesnt work, i can go into my keybinds and change the PTT for the radio to any other key but that doesnt effect the controller setup, its still bound to A on a controller. I play in Redline and everyone that uses a controller says they have the same issue but there is no way to remap the controller. I spent about an hour yesterday trying to figure out a way to fix it. even if i go into the pugins in TS and disabled the controller keybinds as a whole and it still does it

**Comment by Itokoyamato** [comment]
Default keybind for radio is caps. If you don't like it, ask the server owners to change the configuration
Not a tokovoip issue

**Comment by Princejay21** [comment]
the reason that this doesnt make sense is why would it still happen if i change the keybind off caps lock and 2 it just started happening with the new update! Caps Lock has been the default Key for ages now... why would it work fine then the next day i download an update and its changed but its not a tokovoip issue?
