### ISSUE TITLE
TokoVOIP does not connect to client/teamspeak

### ISSUE THREAD

**Issue by Robijntjee** [Itokoyamato/TokoVOIP_TS3#164]
I am trying to get the newest TokoVOIP working, i changed all the necessary configuration and followed the readme, and i still doenst want to work..

I've tested multiple TokoVOIP TS3 Plugins but also this was without any succes..
![image](https://user-images.githubusercontent.com/51093268/88258447-7bbd1d80-ccc0-11ea-9f00-072577a147a0.png)

I host the TeamSpeak server by ZapHosting, but our port is 9030, could this be the problem?
If you guys need any more information about ws_server/TokoVOIP i will see it probably down here.. 

Thanks.

**Comment by mrfuge** [comment]
I'm having the same problem, my co-owner tried upgrading from the original version where ws_server was introduced and getting the same effect, i've been trying as well to no avail.

**Comment by bwheatley** [comment]
So far i'm having no luck with the new version, even with wsserver, it's not even outputting any logs to help debugging, guess revert is in order.

**Comment by ReflexShow** [comment]
Same, please give us a solution.

**Comment by Robijntjee** [comment]
I've installed the ws_server on a differant way instead of using it as a resource. Just follow this [tutorial ](https://www.youtube.com/watch?v=jCwca3SIHC8) and you will probably get out it yourself.
