### ISSUE TITLE
TOKOVOIP issue with fivem

### ISSUE THREAD

**Issue by heisenberg512** [Itokoyamato/TokoVOIP_TS3#167]
Hey, i downloaded tokovoip recently but it wont connect to fivem. I dont know why this happening, i have used it before and it worked completely fine but now its having some sort of connection issue.
![Screenshot (154)](https://user-images.githubusercontent.com/39162506/88440016-29960c80-ce26-11ea-8084-b46a01904ba4.png)

Kindly tell me how to fix this.

**Comment by 69edgy420me** [comment]
Yep. Bad update. No documentation.

**Comment by Poggicek** [comment]
> No documentation.

???? Are you fucking blind dude? You should learn shit about computers and then make a fivem server.

**Comment by Itokoyamato** [comment]
From the fivem logs, it appears this server has not updated to tokovoip 1.5.x.
Download tokovoip 1.2.5 or ask them to update the server.

**Comment by 69edgy420me** [comment]
> > No documentation.
> 
> ???? Are you fucking blind dude? You should learn shit about computers and then make a fivem server.

The documentation doesn't cover all features and is very vaguely written. 

You seem like a real clever guy. You really needed to abuse me for that. Hope you're happy irl mate.
