### ISSUE TITLE
BUG: 2 player from 1 ip is same?

### ISSUE THREAD

**Issue by Deniel00** [Itokoyamato/TokoVOIP_TS3#168]
Hello!

Have 2 player from 1 ip and this 2 player got same data from ws_server, so call A and B player...
B player name in TS3 server same with A player.
If B player at vehicleshop and A player in paletobay, B player hear all players around A player. (Like B player at A player)
I think who play 1 ip ws_server send same data, becouse not check player identity (only ip?)

**Comment by Poggicek** [comment]
Yeah ofc its gonna dod that bullshit if these 2 players join at the same time. There's no other way of identifying the user other than using his ip. If they don't join at the same time it will work as its being only used when handshaking

**Comment by Deniel00** [comment]
We now testing it.
A player join about 18:10, B player join about 18:30. now work corrently.
We run some test whit this.
TS3 Plugin maybe generate identity or use ts3 global identity? (i don't known it possible or not, I just think)

**Comment by Itokoyamato** [comment]
Unfortunately no communication can be made between fivem and TS3, so I can't make a matching identity between the two easily. The easiest thing to use is public IP, which is being used right now. We'll have to settle with one player joining before the other for now.
