### ISSUE TITLE
Tokovoip activation key

### ISSUE THREAD

**Issue by Jouvik** [Itokoyamato/TokoVOIP_TS3#176]
Hi friends,

Is it possible to change the basic activation key? I know that the standard key is CAPS but for some reason I have a radio under the L ALT key but it collides with other keys in the game.

Is it possible to change the activation key somewhere and somehow? unfortunately, it is not possible to use the transmitter at all.

Please be very desperate for some advice

Thank
Jouvik

**Comment by chrisrogersukgb** [comment]
The Radio key can be changed in the c_config file for the tokovoip_script, and will be responsible for the server administrator to change, this can not be changed client side, the only key that can be changed client side is the standard push to talk key, which is set in your Teamspeak 3 Client.

**Comment by Jouvik** [comment]
It's weird that the co-players on the server have a CAPS activation key, but only I have the LEFT ALT as the only one on the server.

**Comment by blk07shelbygt** [comment]
You change it in your keybinds. Go to settings > keybinds >car boats and bikes and change the bicycle sprint key to whatever you want your radio key to be.

**Comment by Jouvik** [comment]
> 
> 
> You change it in your keybinds. Go to settings > keybinds >car boats and bikes and change the bicycle sprint key to whatever you want your radio key to be.

Hi, you're a genius that it's a bind to sprint on a bike I wouldn't have thought of in a million years :) and I gave it up after many hours of googling :)

thank you very much **blk07shelbygt** without you i would be lost forever :)

**Comment by blk07shelbygt** [comment]
> > You change it in your keybinds. Go to settings > keybinds >car boats and bikes and change the bicycle sprint key to whatever you want your radio key to be.
> 
> Hi, you're a genius that it's a bind to sprint on a bike I wouldn't have thought of in a million years :) and I gave it up after many hours of googling :)
> 
> thank you very much **blk07shelbygt** without you i would be lost forever :)

Lol you’re welcome.
