### ISSUE TITLE
Remove blockingscreen

### ISSUE THREAD

**Issue by Joelelfstrom** [Itokoyamato/TokoVOIP_TS3#197]
Hi! This blocking screen, can it be removed? Maybe add option in config to remove it? I've tried to remove/edit html but then it fucks up esx_identity

**Comment by rhapidfyre** [comment]
Edit the CSS and remove the black background.

**Comment by Joelelfstrom** [comment]
I did just set all of and width height to 0 in the HTML.
Then it fucked up esx_identity, so I added Citizen.Wait(2000) before it opens esx_identity UI.

So it's fixed!
