### ISSUE TITLE
PLUGIN status stays offline

### ISSUE THREAD

**Issue by Donrskbb** [Itokoyamato/TokoVOIP_TS3#202]
Some of my players on FiveM just cant join our server bcs the pluginstatus is staying offline for them. I have updated everything. https://cdn.discordapp.com/attachments/729850205058367509/756507407324020796/unknown.png

How can i fix this?

**Comment by dadofender** [comment]
Same issue, tried different settings: hosted TS and the server on my VPS, or hosting locally both TS and server, and various combinations.. For 70% of my players, it works flawlessly.. the rest is still struggling joining the game..
They try to join all day, and they get to play once in maybe 20 tries..
Did you find a solution?

**Comment by Donrskbb** [comment]
Nope still not fixed! I hope they will create a solution.

**Comment by JMansonUG** [comment]
This problem is still present for a few players, No solution found thus far

**Comment by tyzez** [comment]
its still givin us trouble cuhh

**Comment by Donrskbb** [comment]
> its still givin us trouble cuhh

How are you running your WS server?
