### ISSUE TITLE
plugin status OFFLINE, FiveM/Ts3 websocket not connected and plugin not found 

### ISSUE THREAD

**Issue by VenomousOath** [Itokoyamato/TokoVOIP_TS3#217]
![tkvoip](https://user-images.githubusercontent.com/73377654/97068884-026af900-1628-11eb-9bed-ad3f5a96c5ef.PNG)
tried setting up a server, seemed like it was all going to work till i tried to connect. getting the errors listed in the title. (no errors in the fivem console) not sure if its something i did wrong or if its an issue with TokoVOIP, but i have tried fresh setups TokoVOIP and its requirements (ws_server) twice. tried reinstalling teamspeak and the Ts3 plugin twice and no luck. not sure if this is the issue but i am connecting to both the TS server and fivem server from a LAN connection

**Comment by jdrake81** [comment]
THIS iS STILL AN ISsUE AND HAS BEEN FOR MONTHS> PLEASE FIX THIS!

**Comment by senasiaga** [comment]
any solutions?

**Comment by CGod-dev** [comment]
It does not work on LAN

**Comment by VenomousOath** [comment]
i got it working on LAN, perfectly in fact. but still can not get it to work for anyone not on my LAN, so have moved on to other options

**Comment by Horam619** [comment]
How can i fix his issue?

**Comment by chnehla** [comment]
> ![tkvoip](https://user-images.githubusercontent.com/73377654/97068884-026af900-1628-11eb-9bed-ad3f5a96c5ef.PNG) tried setting up a server, seemed like it was all going to work till i tried to connect. getting the errors listed in the title. (no errors in the fivem console) not sure if its something i did wrong or if its an issue with TokoVOIP, but i have tried fresh setups TokoVOIP and its requirements (ws_server) twice. tried reinstalling teamspeak and the Ts3 plugin twice and no luck. not sure if this is the issue but i am connecting to both the TS server and fivem server from a LAN connection

did u find the solution ?
