### ISSUE TITLE
Radio users stop being able to hear other radio users over time

### ISSUE THREAD

**Issue by zbadrabbit** [Itokoyamato/TokoVOIP_TS3#23]
Over time we have radio users unable to hear some other radio users. After they all leave the channel and rejoin the radio channel then everyone can hear again. 

I haven't been able to absolutely pin down when this occurs but it happens enough that we have an OOC message specific for this kind of event. 

No apparent issues with phone calls initiated with using the same function (addUserToRadio) though they tend to be short and person-to-person. 

This has been occurring for at least a month or more now and I only bring it here because I noticed another server having the same kind of issue.

**Comment by Itokoyamato** [comment]
Several changes and bug fixes are in PR #25, will have to see if the issue persists after that

**Comment by Itokoyamato** [comment]
Does that still happen with the latest version of the script(1.3.4) and plugin(1.2.5) ?

**Comment by zbadrabbit** [comment]
We're doing full testing right now. We just upgraded to the 1.2.5 and 1.3.4 and everything seems to be smooth as butter. I'll close this for now. Thank you for the hard work
