### ISSUE TITLE
Screen goes "black" as the info thing pops up some times.

### ISSUE THREAD

**Issue by AdrineX** [Itokoyamato/TokoVOIP_TS3#26]
For every player (on slower pc's it's even worse) screen flickers like the script thinks u are not connected to channel or on teamspeak and works after some time and does it again, not sure what does it but for some users it's annoying (slower pc users as the black screen stays longer).

**Comment by XcentriXTV** [comment]
I’m having the same issue... the tokovoip screen pops up, says it’s the right version, but says initazling then it says wrong teamspeaker server and then it lets me back in and it does this every ten minutes or so, I manage to get from mrpd to the bank and in that time it does it 3 times makes it really unplayable

**Comment by Itokoyamato** [comment]
This should be fixed in the upcoming update (#25)
A timer has been added to allow some latency on slower machines.
