### ISSUE TITLE
Html base distored.

### ISSUE THREAD

**Issue by CSedat** [Itokoyamato/TokoVOIP_TS3#28]
After 30 minutes all html base distortion issue continues.

https://w.wew.wtf/bbwcnm.jpg

**Comment by Autwey** [comment]
That looks like a gcphone issue not Tokovoip.

**Comment by CSedat** [comment]
This picture is an example. it breaks all scripts that work with html.

**Comment by Xteaw** [comment]
Same issue here ^^ and no its not from gcphone, every script using nui/dui (so html or js) is broke after 1h playing

**Comment by Itokoyamato** [comment]
That's NUI getting overwhelmed and not handling the amount of events sent. It should've been mostly fixed in the previous version tho. Some more optimizations have been made in PR #25. Will need to keep an eye on that if it's still an issue once those changes make it to master.

**Comment by Xteaw** [comment]
> That's NUI getting overwhelmed and not handling the amount of events sent. It should've been mostly fixed in the previous version tho. Some more optimizations have been made in PR #25. Will need to keep an eye on that if it's still an issue once those changes make it to master.

I'm 100% sure that it will not resolve the problem since i always used dev branch (so the branch with PR #25) and the problem was still here ^^

**Comment by Itokoyamato** [comment]
Does that still happen with the latest version of the script(1.3.4) and plugin(1.2.5) ?

**Comment by CSedat** [comment]
No

**Comment by CSedat** [comment]
i fixed it
