### ISSUE TITLE
ws_server Not Installing

### ISSUE THREAD

**Issue by Plactrix** [Itokoyamato/TokoVOIP_TS3#315]
When I try to start ws_server, It fails to build
I've asked multiple people and ive tried multiple things, but it doesnt want to work
Yarn, Node and NPM are all up to date

> [ citizen-server-impl] Running build tasks on resource ws_server - it'll restart once completed.
> [ citizen-server-impl] Couldn't start resource ws_server.
> yarn install v1.22.5
> warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> error meow@10.1.0: The engine "node" is incompatible with this module. Expected version ">=12.17". Got "12.13.0"
> error Found incompatible module.
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> [ citizen-server-impl] Building resource ws_server failed.
> [ citizen-server-impl] Error data: yarn failed!

**Comment by zMarkoh** [comment]
have you solved the problem?

**Comment by KingDaria** [comment]
does any one knoew how to fix it i have the problem too
