### ISSUE TITLE
TokoVOIP stuck on Initializing after 7/8/2019 FiveM Update

### ISSUE THREAD

**Issue by Grimsbeard** [Itokoyamato/TokoVOIP_TS3#32]
Looks like FiveM released an update and broke us on TwitchRP. Here is a log snippet

> [     77296] TokoVoip: Initialized script (1.3.2)
> [     77296] nui://tokovoip_script/nui/script.js:38, TokoVOIP: attempt new connection
> [     77296] 
> [     77312] nui://tokovoip_script/nui/script.js:42, TokoVOIP: connection opened
> [     77312] 
> [     77453] EndpointMapper::HandleRequest: GET /cloud/11/cloudservices/titles/gta5/pcros/bgscripts/bg_ng_1604_0.rpf
> [     77531] Error resuming coroutine: @tokovoip_script/src/c_main.lua:110: attempt to index a number value
> [     77531] stack traceback:
> [     77531]     @tokovoip_script/src/c_main.lua:110: in function 'clientProcessing'
> [     77531]     @tokovoip_script/src/c_TokoVoip.lua:34: in function <@tokovoip_script/src/c_TokoVoip.lua:31>
> [     77562] Mumble_RunFrame: capture device changed in GTA code, changing to index 0 (last -1)
> [     77562] Mumble_RunFrame: this device index is GUID {CF688F61-3100-4A5A-A14E-30311B4A3A17}
> [     77562] Mumble_RunFrame: device should've changed by now!
> [     77562] Returning device Speakers (Logitech G933 Gaming Wireless Headset) for GUID {284773BB-93A7-4F46-B390-D17F104BB41A}

From speaking to one of the devs, looks like the call on line 110 was trying to get Gameplay Camera Rotation to determine the sound orientation. Appears that this was changed to a number and not a vector:

17:57] Rinn: GetGameplayCamRot()
[17:57] Rinn: looks like that is returning a number instead of a vector

**Comment by xxRiGaRDoxx** [comment]
set headingType = 1 in c_config util fix is there.

**Comment by Itokoyamato** [comment]
Like @xxRiGaRDoxx said, you can temporarily set `headingType` to 1 in the config, it will use the ped's rotation to calculate audio rather than camera.
Thanks for the report, i'll wait to see if fivem changes it back by tomorrow, if not i'll adapt the script to reflect this change.

**Comment by Autwey** [comment]
I'm not getting that issue. Granted im not using Mumble. I'm not on OneSync

**Comment by AdrineX** [comment]
I'm n ot getting these issues either, and i'm using OneSync, maybe server build is too old ?

**Comment by Itokoyamato** [comment]
Should be fixed in script 1.3.3
