### ISSUE TITLE
Not able to talk on TS after used removePlayerFromRadio

### ISSUE THREAD

**Issue by Xteaw** [Itokoyamato/TokoVOIP_TS3#33]
So here is my code 
`				if CurrentFreq ~= "Aucune fréquence" then
					if exports.tokovoip_script:isPlayerInChannel(CurrentFreq) == true then
						exports.tokovoip_script:removePlayerFromRadio(CurrentFreq)
					end
				end`

when removeplayerfromradio is used, i cant talk on TS, idk whats wrong with this function

**Comment by Xteaw** [comment]
J'ai vu que t'étais FR ^^ Du coup j'explique mieux mon prob, apres avoir fait removePlayerFromRadio, je ne peux plus parler sur TS, j'ai le rond bleu (foncé) mais quand je parle il ne s'allume plus en bleu clair je suis obligé de déco reco du TS ^^

**Comment by Itokoyamato** [comment]
Si tu utilise l'activation vocale, ce n'est pas supporté par le plugin actuellement. Uniquement le push-to-talk.

**Comment by Xteaw** [comment]
D'acc merci de ta réponse ;)
