### ISSUE TITLE
HTML crash apres 1h de jeu

### ISSUE THREAD

**Issue by Xteaw** [Itokoyamato/TokoVOIP_TS3#35]
Je refais un ticket identique au #28 (sry d'avance) en francais pour que tu comprenne mieux le soucis, en gros au bout de 30min voire 1h de jeu, toute les resources utilisant NUI (donc de l'html ou du js) crash instant (exemple le menu ESX et j'en passe). J'essaie de fournir plus d'infos et potentiellement un fix des que je peux.

**Comment by Itokoyamato** [comment]
Merci du retour. J'ai pris conscience du bug, en espérant que la PR #25 aide un peu avec ce bug. Gardons la conversation au même endroit en attendant. ;)
Duplicate of #28
