### ISSUE TITLE
Push to Talk vs Voice Activation Detection

### ISSUE THREAD

**Issue by n3str1x** [Itokoyamato/TokoVOIP_TS3#37]
Hi, 
Thank you for your support, this system is beautiful and in the future I will be contributed for you improve both for this platform and for others.

I have a question to ask.
Sorry for my English, I'm Brazilian using google translator.

On a FiveM server I have a radio that uses the CapsLock key.
However, if I put Voice Detection on TeamSpeak and use this radio in game, my voice detection no longer works. I'm forced to use Push to Talk on TeamSpeak. I wonder if there is any way to fix this.

**Comment by Itokoyamato** [comment]
Hi,
Voice Detection is currently not supported, with no immediate plans for it.
You'll have to use Push to Talk for now.
