### ISSUE TITLE
Update Check

### ISSUE THREAD

**Issue by hsinankirdar** [Itokoyamato/TokoVOIP_TS3#42]
Can i close update check. Because i do not want to update it and a popup notification opening while i am in role play. This notification minimizing the game. 
?
![Toko](https://user-images.githubusercontent.com/12736581/61659543-58881880-acd0-11e9-914d-2aca922f211a.png)

**Comment by shredxt** [comment]
Don't close it, move it off the side of your screen.

**Comment by hsinankirdar** [comment]
this not about me. FiveM Server which i joined, gave that instruction to me. Do not update it!

**Comment by hsinankirdar** [comment]
BTW i blocked github from hosts file, but this is not worked. Updates are still checkable. What is the server link for update check?

**Comment by zbadrabbit** [comment]
the update url is: http://itokoyamato.net/files/tokovoip/tokovoip_info.json

**Comment by Itokoyamato** [comment]
The update only happens on startup on the latest versions of the plugin. Like @shredxt said, a lot of fixes and optimization has been done in recent updates, you should advise your server that they should update.

On the older versions the update link is http://itokoyamato.net/files/tokovoip/tokovoip_version.txt
