### ISSUE TITLE
Voip consistency >= 100 players

### ISSUE THREAD

**Issue by RRavage** [Itokoyamato/TokoVOIP_TS3#47]
Wanted to bring this back up as toko actually crashes after  hitting 100 players. It starts with the inability to hear each other - I don't know if this is a script issue so much as an issue with the plug in itself.

I show myself speaking with others unmuted but we do not hear each other. Teamspeak eventually crashes, as well as no longer showing the server that toko is working. This happens to ALL players on the server.

https://github.com/Itokoyamato/TokoVOIP_TS3/issues/29

**Comment by ronaldoparanhos** [comment]
Same problem here.
Any updates about it?

**Comment by RRavage** [comment]
This is a teamspeak issue. Right click the channel, click "Edit Channel" . Click the advanced tab and change "max users" to unlimited.
