### ISSUE TITLE
add a channel not to Call with radio.

### ISSUE THREAD

**Issue by hemato** [Itokoyamato/TokoVOIP_TS3#48]
guys there is a one room
and 3 player
how to set this 3 people to 3 different channel ? not to radio.
i do
exports.tokovoip_script:addPlayerToRadio(xx)
but when i do like this . nearest people can hear me. how to add player to channel not to Call with raido. ? like we are far from each other. ?

**Comment by Itokoyamato** [comment]
Close by players will always hear others talking. It's not possible de separate players entirely currently.
