### ISSUE TITLE
Api

### ISSUE THREAD

**Issue by Ka1r02** [Itokoyamato/TokoVOIP_TS3#49]
How do i fix this

![ts3client_win64_yJM04cPN1l](https://user-images.githubusercontent.com/53983544/62827618-30eae880-bbca-11e9-91b7-0bb302bc4299.png)

**Comment by RussianRonin** [comment]
Update your teamspeak if it is not up to date.

**Comment by rex2630** [comment]
Update your teamsoeak and tokyoVOIP plugin.
