### ISSUE TITLE
Create channel and plugins?

### ISSUE THREAD

**Issue by Matetv** [Itokoyamato/TokoVOIP_TS3#50]
How can I change to the police channel as an (example) police officer? 
Do I have to set the channels first or create a channel?
If I use the radio script (https://github.com/lakilea/esx_croone_walkietalkie) and talk to a channel there and finish it again, then other players will not hear me anymore and in the TS (leaving the game) you will not hear me anymore!

**Comment by Itokoyamato** [comment]
You will have to ask the script's creator for more specific help.
You first have to create the channel, then join it.
