### ISSUE TITLE
doSendNuiMessage error

### ISSUE THREAD

**Issue by papabendi** [Itokoyamato/TokoVOIP_TS3#51]
Used to use tokovoip perfectly fine, but now it doesn't seem to start correctly with thes server. When I do a manual start or restart of the script I get this:

SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:878: No such export doSendNuiMessage in resource tokovoip_script

> handler (@tokovoip_script/c_config.lua:55)

I cannot seem to figure out what is causing it...

**Comment by bathorus** [comment]
Hi, I got the same error, @papabendi did you find the solution? Would you mind to share it here? Thank you in advance! :)

**Comment by bathorus** [comment]
I found the solution, so don't ever change the folder name from `tokovoip_script` to anything because it contains javascript. Keep it that way, the folder name. Hope it helps.

**Comment by papabendi** [comment]
You can rename it, but you have to go through the script and change a couple of things. Recommended not to do this though. My issue was a lot simpler, we had two versions of it running. Somehow we duplicated the folder and it was interfering.
