### ISSUE TITLE
Auto-connect to Teamspeak server on initialize

### ISSUE THREAD

**Issue by kidheracles** [Itokoyamato/TokoVOIP_TS3#52]
Can the switch to game channel function be extended to first connect the Teamspeak client to the correct Teamspeak server? This would cut back heavily on the number of Teamspeak server licenses, as players can sit with their Teamspeak clients open but disconnected; FiveM servers with >100 players quickly hit the standard 128 server slot limit if there is a significant player queue.
This would also do away with FiveM players having to configure their Teamspeak server settings.

We'd also need a Teamspeak server password setting

**Comment by Itokoyamato** [comment]
Unfortunately this will prove to be difficult to implement now that the system changed in 1.5.0 and I can't get data locally anymore.
