### ISSUE TITLE
Unresolved Externals - Building Solution

### ISSUE THREAD

**Issue by jamie-simmonds** [Itokoyamato/TokoVOIP_TS3#53]
Hi

I'm quite new to c++/c so sorry if this is a basic mistake.

When I try to build the plugin solution in VS I get the following errors:

![image](https://user-images.githubusercontent.com/5081482/63268771-dbc76a80-c28c-11e9-8ca1-37ec03026d7a.png)

Any idea what I am doing incorrectly?

Thanks,
Jamie

**Comment by Poggicek** [comment]
you have to only build "tokovoip" solution
