### ISSUE TITLE
force equalizing people voice sending parameters

### ISSUE THREAD

**Issue by tbgiarreta** [Itokoyamato/TokoVOIP_TS3#54]
It would be possible to force equalizing people's voice by sending the parameters (low_freq, high_freq, fudge, rm_mod_freq, rm_mix, o_freq_lo, o_freq_hi) along with the radioEffect = true parameter that is already sent in the c_main.lua file, and ignoring the setting made by the user on Radio FX. I would like to create a default setting for the radio and with the same voice effect for everyone on my server. If there is already the possibility I ask you to help me how should I send the parameter.

**Comment by Itokoyamato** [comment]
Adding a configuration for that proves a bit troublesome, and I don't want to force it on everyone. Will have to see if it's possible later
