### ISSUE TITLE
RadioFX does not work for some radio members

### ISSUE THREAD

**Issue by martin951** [Itokoyamato/TokoVOIP_TS3#55]
As the title suggests, RadioFX effect does not apply to some users talking through the radio

**Comment by kuuttithe** [comment]
Can confirm. RadioFX effects don't apply.

**Comment by martin951** [comment]
You can sort of fix the issue by reloading the plugin.

**Comment by kuuttithe** [comment]
> You can sort of fix the issue by reloading the plugin.

Didn't help, i was trying to figure out too how to switch the radio effects if possible lol

**Comment by martin951** [comment]
> > You can sort of fix the issue by reloading the plugin.
> 
> Didn't help, i was trying to figure out too how to switch the radio effects if possible lol

It helps if I connect to the radio, and then reloading it. All ussers allready connected to same channel then have the effects applied. But it might be a serverside thing aswell, idk.

**Comment by kuuttithe** [comment]
> It helps if I connect to the radio, and then reloading it. All ussers allready connected to same channel then have the effects applied. But it might be a serverside thing aswell, idk.

https://i.imgur.com/34Tt637.png  
You can also try messing with the radiofx buttons and then refreshing tokovoip, seemed to help me a lil bit.

**Comment by Azaun** [comment]
If you have RadioFX installed as a stand-alone plugin as well as TokoVOIP it seems to create a conflict. When I removed the stand-alone RadioFX plugin it seemed to resolve a similar sounding issue for me.

**Comment by FearPredator** [comment]
Initially it was enough for me to reload the addon to solve.
Right now, I no longer hear the radio with the RADIO FX effect

**Comment by Itokoyamato** [comment]
Tokovoip 1.5.0 has been [released](https://github.com/itokoyamato/tokovoip_ts3/releases) and includes an update to RadioFX
Please try again once your server is updated to tokovoip 1.5.0. (don't update your teamspeak plugin until the server you play on updates as well)
Feel free to open a new issue if the problem persists on the latest versions.
