### ISSUE TITLE
people not getting locally muted

### ISSUE THREAD

**Issue by Zerefdev** [Itokoyamato/TokoVOIP_TS3#56]
Hello,

I can hear everyone on the channel, the local mute/unmute is not working!
TS Version: 3.2.2
Plugin Version : 1.2.5

**Comment by Cmoen11** [comment]
Same issue here, did you resolve it?

**Comment by Zerefdev** [comment]
```
        TSChannelWhitelist = { -- Black screen will not be displayed when users are in those TS channels
        },
```
this was the problem for me, I put TSChannel there as well. Apparently, this must stay empty
