### ISSUE TITLE
Problem with  a 100+ players

### ISSUE THREAD

**Issue by ronaldoparanhos** [Itokoyamato/TokoVOIP_TS3#58]
So when has more then 99 players on server , the teamspeak mute all and stop working.

I tried the solution on this issue: https://github.com/Itokoyamato/TokoVOIP_TS3/issues/47

By @RRavage 
> "This is a teamspeak issue. Right click the channel, click "Edit Channel" . Click the advanced tab and change "max users" to unlimited."

But the still problem ocorry, only work if i limit server and channel to 99 players.

**Comment by Doxylamin** [comment]
Can confirm this with 150+ players.

**Comment by ronaldoparanhos** [comment]
> Can confirm this issue happens as soon as you hit 100 players in the voice chat. Gets even worse with 128+ where sometimes it doesn't update the position of others and they remain muted.
> 
> Edit: Also, Tokovoip seems spamming the shit out of the clients, sending "setPlayerData" with a payload between 17-20 Bytes every few milliseconds.
> ![image](https://user-images.githubusercontent.com/14816200/71376601-4d5c5000-25c2-11ea-9bca-def81b55124f.png)

Yeah its so bad, u have any news about it?

**Comment by achrafhammani** [comment]
same problem +72 player

**Comment by minipunch** [comment]
Would like to know the problem behind this as it is happening to our server as well.

Works fine at 90 slots but when we set our server to 100 slots then every few minutes everybody's voice completely mutes for a minute or two and then goes back to normal. It repeats that issue extremely consistently; making it unplayable at 100 or more players.

**Comment by Itokoyamato** [comment]
Tokovoip 1.5.0 has been [released](https://github.com/itokoyamato/tokovoip_ts3/releases) and has full support for onesync infinity.
Please try again once your server is updated to tokovoip 1.5.0. (don't update your teamspeak plugin until the server you play on updates as well)
Feel free to open a new issue if the problem persists on the latest versions.
