### ISSUE TITLE
Some clients are not able to communicate with the ts3 plugin

### ISSUE THREAD

**Issue by ArMaTeC** [Itokoyamato/TokoVOIP_TS3#59]
So since using toko we have has the same recurring issue that is random for me but some have it happen permanently the issue is that although i/they have the plugin on ts3 enabled the game will not see it as enabled 

![0e7b59e9ac8a96cd5aee62ccbc8f3b41](https://user-images.githubusercontent.com/3974913/65368245-8937f000-dc36-11e9-81b5-98740ac85e98.png)

This is only 2 refs to toko in the CitizenFX log when it dose not work and 4 when it dose so for some reason its not initialized
{BROKEN}
[tokovoip_script]
Creating script environments for tokovoip_script

{WORKING}
[tokovoip_script]
Creating script environments for tokovoip_script
TokoVoip: Initialized script (1.3.4)
nui://tokovoip_script/nui/script.js:40, TokoVOIP: attempt new connection
nui://tokovoip_script/nui/script.js:44, TokoVOIP: connection opened

I know there is not much info here but im trying

**Comment by Itokoyamato** [comment]
This is most likely a firewall issue
