### ISSUE TITLE
Api version is not compatible

### ISSUE THREAD

**Issue by zbadrabbit** [Itokoyamato/TokoVOIP_TS3#6]
Newest TS3 update causes TokoVOIP plugin to fail to load

TS3 version 3.3.0 (6/18/2019)
"Api version is not compatible: 22 (minimum 23, current: 23)"

**Comment by omarocasio** [comment]
I updated the plugin to work with new API

Check forums
https://forum.fivem.net/t/release-tokovoip-a-teamspeak-based-voip-system/475479/149

**Comment by floppypancakes4u** [comment]
Confirmed by several other reporters.

**Comment by Itokoyamato** [comment]
Fixed in #9 
New release available [here](https://github.com/Itokoyamato/TokoVOIP_TS3/releases/tag/v1.2.2-v1.2.10)

**Comment by amauryferrin** [comment]
Api version is not compatible: 23 (minimum 21, current: 22)
como lo soluciono
