### ISSUE TITLE
Normal voice stops working after using radio

### ISSUE THREAD

**Issue by MiezLP** [Itokoyamato/TokoVOIP_TS3#62]
Everything is working fine until i use the radio, the radio itself works but after talking there my microphone practically stops working in team speak and i cannot speak anymore. Please help
https://pastebin.com/MGg6vk1h

**Comment by Azaun** [comment]
Are you using VoiceActivated mode? I have seen this issue with a few other people as well who are using VA. As soon as they use a radio or a phone they lose the ability to speak to people around them. Trying to find a solution to this for some friends.

**Comment by rex2630** [comment]
Yeah this issue is pretty anoying. Waiting for fix

**Comment by DomePwny** [comment]
```
if (radioTalking)
		{
			setClientTalking(true);
			if (!isTalking && radioClicks == true && local_click_on == true)
				playWavFile("mic_click_on");
			isTalking = true;
		}
		else
		{
			if (isTalking)
			{
				setClientTalking(**false**);
				if (radioClicks == true && local_click_off == true)
					playWavFile("mic_click_off");
				isTalking = **false**;
			}
		}
```
Isnt it wrong? The talking status is set to false after the radio talk? Maybe its the problem for the VoiceActivation.

**Comment by rex2630** [comment]
So did anyone tried to change it?

**Comment by Marzouz** [comment]
Up ?

**Comment by rex2630** [comment]
U dont need too. This script is completely dead

**Comment by Itokoyamato** [comment]
Tokovoip 1.5.0 has been [released](https://github.com/itokoyamato/tokovoip_ts3/releases) and includes improvements to the voice detection system
Please try again once your server is updated to tokovoip 1.5.0. (don't update your teamspeak plugin until the server you play on updates as well)
Feel free to open a new issue if the problem persists on the latest versions.
