### ISSUE TITLE
Teamspeak halt on Couldn't retrieve JSON (Code: 0) Windows 10 Pro 

### ISSUE THREAD

**Issue by mountainman38** [Itokoyamato/TokoVOIP_TS3#66]
ts will halt for about 10+ mins with this error in log and then will open normally i have tried reinstalling ts and plugin tried on another windows 10 pc and even on a windows 7 rig to no avil same issue across 3 pcs with all three having very different hardware... i have attached a log so you can see what is going on 
[ts3client_2019-12-18__01_45_41.684063.log](https://github.com/Itokoyamato/TokoVOIP_TS3/files/3977063/ts3client_2019-12-18__01_45_41.684063.log)

**Comment by Itokoyamato** [comment]
Tokovoip 1.5.0 has been [released](https://github.com/itokoyamato/tokovoip_ts3/releases) and should be more stable
Please try again once your server is updated to tokovoip 1.5.0. (don't update your teamspeak plugin until the server you play on updates as well)
Feel free to open a new issue if the problem persists on the latest versions.
