### ISSUE TITLE
TokoVOIP Not Working

### ISSUE THREAD

**Issue by Mart475** [Itokoyamato/TokoVOIP_TS3#67]
Hello.

I recently installed TokoVOIP however I can hear players on the other side of the map. I made a forum post about it here.

https://forum.fivem.net/t/release-tokovoip-a-teamspeak-based-voip-system/475479/590

Still getting the same issue, not sure how to setup the teamspeak channels or the script itself, please help me.

Thanks.

**Comment by nicktrick92** [comment]
> Hello.
> 
> I recently installed TokoVOIP however I can hear players on the other side of the map. I made a forum post about it here.
> 
> https://forum.fivem.net/t/release-tokovoip-a-teamspeak-based-voip-system/475479/590
> 
> Still getting the same issue, not sure how to setup the teamspeak channels or the script itself, please help me.
> 
> Thanks.

The first issue is that it appears as though you renamed the script, which you can't do without changing 4-5 lines in the JS file. So, change the script name back to `tokovoip_script`. Secondly, you set up the script with the `cl_config.lua` file. It's pretty self-explanatory in that file. Without a snippet of the config you currently have, I can't help much with that.
