### ISSUE TITLE
License

### ISSUE THREAD

**Issue by barlipdev** [Itokoyamato/TokoVOIP_TS3#69]
Hi, i'm creating a server but i would like to change it a bit in "index.html" but i will leave things like this that the script and plugin is yours. Can i do that?

**Comment by RussianRonin** [comment]
Well, quoting the license:

> On screen displays of TokoVOIP and copyrights must remain visible and readable. You are allowed however to change their position and design. 

So yes... one would assume they can change the look as long as the quoted statement still applies.
