### ISSUE TITLE
Anyone can hear everyone

### ISSUE THREAD

**Issue by dutchplayers** [Itokoyamato/TokoVOIP_TS3#70]
We have the problem since 2 weeks that anyone can hear everyone while talking with TokoVOIP. It did worked before... Anyone got an idea how to solve this?

**Comment by duckhunter392** [comment]
You might have the default voice still enabled. Try having someone turn off their in game voice and see if that fixes the problem.

**Comment by Yedoo** [comment]
> You might have the default voice still enabled. Try having someone turn off their in game voice and see if that fixes the problem.

no it doesn't

**Comment by HamzaLCDP** [comment]
I have the same problem did you get the solution if yes please help 
@Yedoo

**Comment by rheein** [comment]
Same with me :(

**Comment by iiDrop** [comment]
still got this issue, would like to know fix if there is any :)

**Comment by ninjamettin** [comment]
did it get fixed? i have the same problem too

**Comment by Itokoyamato** [comment]
Tokovoip 1.5.0 has been [released](https://github.com/itokoyamato/tokovoip_ts3/releases)
Please try again once your server is updated to tokovoip 1.5.0. (don't update your teamspeak plugin until the server you play on updates as well)
Feel free to open a new issue if the problem persists on the latest versions.
