### ISSUE TITLE
localName not working

### ISSUE THREAD

**Issue by RagingWookie** [Itokoyamato/TokoVOIP_TS3#71]
I have set the TokoVOIP script to set a generic localName for players to prevent Metagaming, but it refuses to change the player's name in Teamspeak:

		localName = "AfricaLife_Citizen", -- If set, this name will be used as the user's teamspeak display name
		localNamePrefix = "[" .. GetPlayerServerId(PlayerId()) .. "] ", -- If set, this prefix will be added to the user's teamspeak display name

**Comment by duckhunter392** [comment]
`AddEventHandler("onClientResourceStart", function(resource)
	if (resource == GetCurrentResourceName()) then	--	Initialize the script when this resource is started
		Citizen.CreateThread(function()
			TokoVoipConfig.plugin_data.localName = escape(GetPlayerName(PlayerId())); -- Set the local name
		end);
		TriggerEvent("initializeVoip"); -- Trigger this event whenever you want to start the voip
	end
end)
`

TokoVoipConfig.plugin_data.localName = escape(GetPlayerName(PlayerId())); -- Set the local name

**Comment by duckhunter392** [comment]
```lua
TokoVoipConfig.plugin_data.localName = escape(GetPlayerName(PlayerId())); -- Set the local name
```
Line 56 in `c_config.lua` resets the value of localname to the players name.
