### ISSUE TITLE
Onesync Infinity

### ISSUE THREAD

**Issue by WooAf** [Itokoyamato/TokoVOIP_TS3#72]
Any eta on the infinity update ?

**Comment by johnnypernik** [comment]
Yes please!

**Comment by Eric1212** [comment]
I second the need,

**Comment by johnnypernik** [comment]
I would like to also notice that only making getting players compatible with Infinity will also need to fix #58 to be futureproof. But it will be big improvement even as a part solution before that.

**Comment by WooAf** [comment]
Onesync infinity: You're connected only when you're close to someone

Tokovoip doesn't mute when you're not connected with someone

That's the biggest problem right now
