### ISSUE TITLE
tokovoip offline

### ISSUE THREAD

**Issue by Sph3x** [Itokoyamato/TokoVOIP_TS3#73]
after last fivem update 
https://cdn.discordapp.com/attachments/564521563731394573/672397502028316683/unknown.png
https://uc.chatra.io/d7654878-e97f-4ca7-b128-c19c1a05cc4b/

**Comment by Iandenh** [comment]
It looks like the latest update FiveM are blocking websockets connection to localhost and 127.0.0.1.

I'm curious if you can make it work to choose a domain name that resolves to 127.0.0.1 by a DNS server.

**Comment by Iandenh** [comment]
Looks like the Blacklist is just changed to allow the port TokoVoip is using .
https://runtime.fivem.net/nui-blacklist.json
```
[
    "coin-?hive\\.com",
    "://localhost:",
    "127\\.[0-9]+\\.[0-9]+\\.[0-9]+:(?:[12456789]|3[123456790])"
]
```

**Comment by LeagueTM** [comment]
So how do I fix this issue? :D Do I just wait for fivem to update?

**Comment by Iandenh** [comment]
The blacklist is recieved here: https://github.com/citizenfx/fivem/blob/e6f441d3a92a4986bb8272825645afe38a713a9c/code/components/nui-core/src/NUIClient.cpp#L46

So I guess just restart FiveM

**Comment by Sph3x** [comment]
Since people are trying to use this topic to post ‘workarounds’ to a (since-removed) policy change, it is locked until further notice.

In addition to that, it’s likely that servers using ‘TokoVOIP’ or other external application dependencies will be removed from the main server list and added to a separate opt-in ‘private’ view. THis is what fivem dev write on fivem.net

**Comment by azarathkhan** [comment]
FiveM admins have stated publicly they have always intended to block TokoVoip when a work around was available, but that they have now unintentionally blocked it indirectly ahead of time via their security "patch" of blocking websockets.

I do not see FiveM rolling this back. The only solution is to run the server unlisted in order to use Tokovoip, which for my community is not a viable choice.

**Comment by Itokoyamato** [comment]
In a recent security update, fivem had blacklisted websockets running on the local network. Tokovoip uses those to communicate with teamspeak. They have whitelisted tokovoip for the time being, but will most likely blacklist it again in the future.

In the meantime, I will be looking for a long term solution

**Comment by xScriptedx** [comment]
> In a recent security update, fivem had blacklisted websockets running on the local network. Tokovoip uses those to communicate with teamspeak. They have whitelisted tokovoip for the time being, but will most likely blacklist it again in the future.
> 
> In the meantime, I will be looking for a long term solution

I need help
