### ISSUE TITLE
TS3 configuration info

### ISSUE THREAD

**Issue by Identity-labs** [Itokoyamato/TokoVOIP_TS3#74]
Hi,

Can we know if the TS are in push to talk or voice activation in script ?

Thx

**Comment by azarathkhan** [comment]
https://github.com/Itokoyamato/TokoVOIP_TS3/issues/37#issuecomment-514744542

A reply was posted to an earlier issues RE: voice activation. It's an issue with TS and the plugin that causes voice activation to break after using the radio portion of Tokovoip.

I also wish there was a fix, but unfortunately that does not seem to be in the books :(. Might be a TS limitation.

**Comment by Itokoyamato** [comment]
Tokovoip 1.5.0 has been [released](https://github.com/itokoyamato/tokovoip_ts3/releases) and has improvements to the voice activation system.
Please try again once your server is updated to tokovoip 1.5.0. (don't update your teamspeak plugin until the server you play on updates as well)
Feel free to open a new issue if the problem persists on the latest versions.
