### ISSUE TITLE
TokoVoip not working

### ISSUE THREAD

**Issue by Lokajn** [Itokoyamato/TokoVOIP_TS3#76]
Hello,
My problem is with TokoVoip…
I turn on the FiveM, I connect to the server then I turn on the TS3 I’m in a room from where it should put me in a room already with Tokovoip, but that’s not going to happen and I’m still in that original room… I still have a screen on FiveM to join TS3. Screenshots are shown below.
(Voice Chat ingame is off)

Gta V Online version is 1.50
2.Original game with original FiveM.
SocialClub.
Windows version.
I try to reinstall TS3 and FiveM too.
I7 4790k, GTX 1080TI, 24GB Ram DDR3, 232GB SSD, 2TB HDD
There is screenshot: https://gyazo.com/c7b104819d7a1b8b406e5ac8fe94d15d 1

**Comment by Lokajn** [comment]
New info! https://gyazo.com/f4c174449538032db2afd668ea969172

**Comment by dezsimartin** [comment]
I have the same problem

**Comment by Itokoyamato** [comment]
My guess would be that some firewall or antivirus is blocking tokovoip's access to the network.
Tokovoip 1.5.0 has been [released](https://github.com/itokoyamato/tokovoip_ts3/releases) and should be more stable
Please try again once your server is updated to tokovoip 1.5.0. (don't update your teamspeak plugin until the server you play on updates as well)
Feel free to open a new issue if the problem persists on the latest versions.
