### ISSUE TITLE
After Using Radio Voice Control is not working

### ISSUE THREAD

**Issue by ZockerBoysHD** [Itokoyamato/TokoVOIP_TS3#78]
Hi there,

After i used tokovoip with the Radio / Call function my teamspeak doesnt respond to my voice activation anymore. Only if i set my Teamspeak to Push-To-Talk im able to talk again. (Or restart TS)

**Comment by Itokoyamato** [comment]
Tokovoip 1.5.0 has been [released](https://github.com/itokoyamato/tokovoip_ts3/releases) and has improvements to the voice activation system
Please try again once your server is updated to tokovoip 1.5.0. (don't update your teamspeak plugin until the server you play on updates as well)
Feel free to open a new issue if the problem persists on the latest versions.

**Comment by GameHostDirect** [comment]
This issue is still happening on 1.5.4

**Comment by ZockerBoysHD** [comment]
> This issue is still happening on 1.5.4

Bro. This thing has been dead since 2020.
I can only reccomend SaltyChat nowadays.
