### ISSUE TITLE
Proximities switch not working.

### ISSUE THREAD

**Issue by Christina1734** [Itokoyamato/TokoVOIP_TS3#79]
I got my server installed this awesome script, but there’s one thing I can’t solve is that the function of changing proximity is not working.

First, I’ve tried to install this script and this only.
And I didn’t change the key settings of the config or client/main.lua whatever....
The key just don’t work well.

However, the other function are works fine to my server.
Plz help me out of this mess.

If you guys need any further information, feel free to ask.

**Comment by Itokoyamato** [comment]
Can't reproduce the issue. Actually never heard of this one before.
Tokovoip 1.5.0 has been [released](https://github.com/itokoyamato/tokovoip_ts3/releases) and should be more stable
Please try again once your server is updated to tokovoip 1.5.0. (don't update your teamspeak plugin until the server you play on updates as well)
Feel free to open a new issue if the problem persists on the latest versions.
