### ISSUE TITLE
How to build Teamspeak Addon with Cmake

### ISSUE THREAD

**Issue by ZockerBoysHD** [Itokoyamato/TokoVOIP_TS3#80]
I downloaded Cmake and QT 5.6 onto my Windows 10 machine, opened the cmake gui, loaded the tokovoip files but there were some dependencies missing (simple-websocket) which isnt available on github anymore. also it said "couldnt find compiler visual studio 15 2019". but i have VS installed.

How do i builkd the TS Plugin myself cause i changed some code and would apreciate to use my own code instead oif the pre-made one.

**Comment by linuxgemini** [comment]
Rule of thumb, [RTFM completely and correctly](https://github.com/Itokoyamato/TokoVOIP_TS3#building-the-ts3-plugin).

It literally tells you to recursively get the submodules **using `git`**. Also, `Simple-WebSocket-Server` is hosted on Gitlab. See the submodule entry below: https://github.com/Itokoyamato/TokoVOIP_TS3/blob/58c15a4f1bca39c743af023d929ab1c81bcc5023/.gitmodules#L1-L3

>  also it said "couldnt find compiler visual studio 15 2019".

That's not a valid VS version tag. [The manual](https://github.com/Itokoyamato/TokoVOIP_TS3#building-the-ts3-plugin) uses `Visual Studio 15 2017` and `Visual Studio 15 2017 Win64` which is the VS tag of (you guessed it) VS2017.

If you are gonna do a very minimal install of VS2017 with Build Tools only, make sure that you have Windows SDK and C++ Extensions also checked on the installer. (Considering you have VS2019, you probably have the Windows SDK installed already.)

Once you are done creating the build environment for both architectures (this includes the build tools terminals for both architectures), you can invoke MSBuild. If you like doing multithreaded compiling, append the `/m` flag to the commands below.

x64 build command: `msbuild TokoVoip.vcxproj /p:Configuration=Release /p:Platform=x64`
x86 build command: `msbuild TokoVoip.vcxproj /p:Configuration=Release /p:Platform=Win32`

Somehow the generated solution `TokoVoip.sln` compiles everything for couple of times, then tries to compile RadioFx and fails. Using the VS project file does solve it.

**Comment by ZockerBoysHD** [comment]
how should i create a VS solution if there no instruction of which type it should be? 

i have the complete files downloaded now. but how can i build it if it doesnt know the cmake command in cmd.

**Comment by ZockerBoysHD** [comment]
https://cdn.egopvp.com/notes/?975ec2ee6e686d5c#Lzjt3UmeRTiqEheUaUBAH59JHJhdujRuuNrZwHyBWso=   thats the error which occures after adding QT directory.

**Comment by Itokoyamato** [comment]
Tokovoip 1.5.0 has been [released](https://github.com/itokoyamato/tokovoip_ts3/releases), please try again with the updated dependencies.
Feel free to open a new issue if the problem persists.
