### ISSUE TITLE
tokovoip RadioKey dont work

### ISSUE THREAD

**Issue by KhaziusGER** [Itokoyamato/TokoVOIP_TS3#82]
The RadioKey dosent work afte the FiveM Client Update 22.02.2020

**Comment by Itokoyamato** [comment]
Works fine. If you're using voice activation, check out Tokovoip 1.5.0 [here](https://github.com/itokoyamato/tokovoip_ts3/releases) and fully supports onesync infinity
Please try again once your server is updated to tokovoip 1.5.0. (don't update your teamspeak plugin until the server you play on updates as well)
Feel free to open a new issue if the problem persists on the latest versions.
