### ISSUE TITLE
Tokovoip connection timed out

### ISSUE THREAD

**Issue by dezsimartin** [Itokoyamato/TokoVOIP_TS3#83]
Greetings.

https://i.imgur.com/1eGNamM.png

When I'm connecting to a specific server, after the plugin inits, it says OFFLINE, and dont recognize, I'm in the right channel. (On other tokovoip servers, its working perfectly, I tried on 4) I reinstalled everything, and I'm using ts latest version with the tokovoip latest version. At the console, usually says: connection timed out, or closed abnormally. I tried with toko 1.2.1 and 1.2.4 version, but it was the same. Or it's server sided problem? But noone has the same problem as me, and there are like 400 players at least. So its specific i guess. My firewall is disabled. Any tips appreciated.

**Comment by Poggicek** [comment]
its says you are connected to a different teamspeak...

**Comment by dezsimartin** [comment]
I can read, but I am connected to the right one.......

**Comment by Poggicek** [comment]
it tells you to join server33.ts3.run:10064 and you are joining redlightrpdelta.tsdns.hu. 2 different domains

**Comment by dezsimartin** [comment]
it was the same, when that TS server was running.

**Comment by Itokoyamato** [comment]
This clearly appears to be a wrong configuration. I would avoid putting ports in teamspeak server connection infos.
