### ISSUE TITLE
Isn't support more than 128 players?

### ISSUE THREAD

**Issue by Nixen07** [Itokoyamato/TokoVOIP_TS3#85]
Do you have any idea about when patch +128 is release?

**Comment by Poggicek** [comment]
soon, you can close

**Comment by Itokoyamato** [comment]
Tokovoip 1.5.0 has been [released](https://github.com/itokoyamato/tokovoip_ts3/releases) and fully supports onesync infinity
Please try again once your server is updated to tokovoip 1.5.0. (don't update your teamspeak plugin until the server you play on updates as well)
Feel free to open a new issue if the problem persists on the latest versions.
