### ISSUE TITLE
TokoVOIP stays offline/doesn't initialize

### ISSUE THREAD

**Issue by Electr0-csgo** [Itokoyamato/TokoVOIP_TS3#87]
Recently i've got some kind of issue... When i connect (and there is more than 50 players) to server and connect to TS3 server, toko stays offline 
![obrázok](https://user-images.githubusercontent.com/62223688/76713541-99caae00-6721-11ea-8e60-cef76e03ef3e.png)
Everything is up-to-date 

I tried 
- clean reintall of - GTAV , FiveM , TS3 , Plugin 
- disabling firewall 

in console or CitizenFX stays 
MainThrd/ TokoVoip: Initialized script (1.3.5)
[    413735] [    GTAProcess]        CrBrowserMain/ Uncaught TypeError: Cannot set property 'innerHTML' of null (@tokovoip_script/nui/script.js:257)
[    413735] [    GTAProcess]        CrBrowserMain/ TokoVOIP: attempt new connection (@tokovoip_script/nui/script.js:39)
[    413891] [    GTAProcess]        CrBrowserMain/ TokoVOIP: connection opened (@tokovoip_script/nui/script.js:43) 

 or mostly just 
Uncaught TypeError: Cannot set property 'innerHTML' of null (@tokovoip_script/nui/script.js:257)
TokoVOIP: attempt new connection (@tokovoip_script/nui/script.js:39)

any fixes or help ?

**Comment by achrafhammani** [comment]
same problem +72 player

**Comment by mrmicheall** [comment]
same same

**Comment by Electr0-csgo** [comment]
I reinstalled windows to factory settings, now it's ok

**Comment by achrafhammani** [comment]
Electr0-csgo How do windows to factory settings

**Comment by achrafhammani** [comment]
delete all files or not ?

**Comment by Itokoyamato** [comment]
Tokovoip 1.5.0 has been [released](https://github.com/itokoyamato/tokovoip_ts3/releases) and fully supports onesync infinity
Please try again once your server is updated to tokovoip 1.5.0. (don't update your teamspeak plugin until the server you play on updates as well)
Feel free to open a new issue if the problem persists on the latest versions.

**Comment by xScriptedx** [comment]
Hello there, I'm currently having an issue where not just me but all my players cannot get past Toko VOIP black screen. Everything is setup perfectly even the console has 0 errors initializes perfectly but OFFLINE - ?

Best regards,
Calvin

**Comment by FancyBean** [comment]
Hello, I too am having this issue. I cannot get past the tokovoip black screen, despite ensuring everything is set up and running currently. I have reinstalled both teamspeak and Tokovoip multiple times but it continues to state “plug in offline.“ Any help with this would be greatly appreciated. Thank you!

Kind Regards,
Chelsea

**Comment by SlimEagle-dev** [comment]
Hey i have the same problem. I tried everything. Restarted my PC, desinstall TS3, tokvoip, fivem, disabling firewall but nothing worked.

**Comment by lilpats** [comment]
My problem is similar, My tokoVOIP initializes and works for a bit then turns back offline. and then i have to restart ts3 and it works again for some time.

**Comment by MulliTA** [comment]
I'm having the same problem, mine is displaying 

Pugin version: Not Found (Required 1.5.0) 

I have everything set up as it should be. New version installed and the server I play on has the new version added.

**Comment by bhoirpushpak** [comment]
Anyone found a solution. I am getting same issue please help.

**Comment by iseeface** [comment]
![Screenshot (787)](https://user-images.githubusercontent.com/67980665/91286448-aa934b80-e7b8-11ea-94a1-10bef87e309e.png)
what happened to my teamspeak? I've been on the correct server and room and I've also installed the latest TeamSpeak3 and TokoVOIP Plugin, but when I return to the FiveM view, the display is always like this. The system says my TokoVOIP is Offline. I don't know what happened, I tried to find a solution but couldn't find it.

**Comment by Izachi** [comment]
Same Issue for me ! I can't play because of that. Any idea how to fix this issue ?

**Comment by shammas101** [comment]
> ![Screenshot (787)](https://user-images.githubusercontent.com/67980665/91286448-aa934b80-e7b8-11ea-94a1-10bef87e309e.png)
> what happened to my teamspeak? I've been on the correct server and room and I've also installed the latest TeamSpeak3 and TokoVOIP Plugin, but when I return to the FiveM view, the display is always like this. The system says my TokoVOIP is Offline. I don't know what happened, I tried to find a solution but couldn't find it.

same can anyone help me pls

**Comment by shammas101** [comment]
> what happened to my teamspeak? I've been on the correct server and room and I've also installed the latest TeamSpeak3 and TokoVOIP Plugin, but when I return to the FiveM view, the display is always like this. The system says my TokoVOIP is Offline. I don't know what happened, I tried to find a solution but couldn't find it.

what happened to my teamspeak? I've been on the correct server and room and I've also installed the latest TeamSpeak3 and TokoVOIP Plugin, but when I return to the FiveM view, the display is always like this. The system says my TokoVOIP is Offline. I don't know what happened, I tried to find a solution but couldn't find it.

**Comment by shammas101** [comment]
> ![Screenshot (787)](https://user-images.githubusercontent.com/67980665/91286448-aa934b80-e7b8-11ea-94a1-10bef87e309e.png)
> what happened to my teamspeak? I've been on the correct server and room and I've also installed the latest TeamSpeak3 and TokoVOIP Plugin, but when I return to the FiveM view, the display is always like this. The system says my TokoVOIP is Offline. I don't know what happened, I tried to find a solution but couldn't find it.

**Comment by sparcoxalpha** [comment]
Same issue ...after 75+ players,not able to connect, some of the players automatically going back to lobby.

**Comment by PilotConnor** [comment]
The only way I was able to join was turning on a VPN which actually fixed the issue 👍

**Comment by canolida** [comment]
hey man i have also this problem too but mine says that plugins status: undefined can someone help me?

**Comment by iseeface** [comment]
> 

if your problem is like mine (see above), you can use a vpn to solve that problem

**Comment by iseeface** [comment]
> hey man i have also this problem too but mine says that plugins status: undefined can someone help me?

if your problem is like mine (see above), you can use a vpn to solve that problem
