### ISSUE TITLE
Can hear people from much further than others on server

### ISSUE THREAD

**Issue by capecodcaper** [Itokoyamato/TokoVOIP_TS3#88]
Hey there,

I am having an issue where I can hear people on the "shout" and "normal" settings at double the distance of everyone else. I can hear people shouting at 2-3 blocks away. It can get really distracting.

I have turned off in game voice, reinstalled TS and Toko. Is there anything I can do?

**Comment by Itokoyamato** [comment]
Tokovoip 1.5.0 has been [released](https://github.com/itokoyamato/tokovoip_ts3/releases) and fully supports onesync infinity
Please try again once your server is updated to tokovoip 1.5.0. (don't update your teamspeak plugin until the server you play on updates as well)
Feel free to open a new issue if the problem persists on the latest versions.
