### ISSUE TITLE
FiveM Blocking localhost / 127.0.0.1 Again

### ISSUE THREAD

**Issue by swat30** [Itokoyamato/TokoVOIP_TS3#89]
A recent FiveM update has broken integration w/ TokoVoIP again:
https://runtime.fivem.net/nui-blacklist.json
https://cdn.discordapp.com/attachments/616638867885522945/690605599813140581/unknown.png

**Comment by djmetla** [comment]
Same issue here: **Blocked a request for blacklisted URI ws://127.0.0.1:38204/tokovoip**

**Comment by ClubNola** [comment]
same issue here

**Comment by Kratorio** [comment]
same issue here

**Comment by TyceTV** [comment]
same

**Comment by Harybo** [comment]
same

**Comment by LaFouine25** [comment]
same

**Comment by arnevdaele** [comment]
FiveM blocked local sockets.
The best solution is proxy through the server.

**Comment by swat30** [comment]
@arnevdaele can you provide some info on how you've done this?

**Comment by chiraqrp** [comment]
@arnevdaele same here

**Comment by thephilluk** [comment]
Seems like FiveM pushed a microchange, for our group of people (5) it works now.

**Comment by oscsystemx** [comment]
same

**Comment by CarlosVergikosk** [comment]
> FiveM blocked local sockets.
> The best solution is proxy through the server.

Can you provide a source or some information of possible fixes? thanks!

**Comment by oscsystemx** [comment]
[
"coin-?hive\.com",
"://localhost:",
"127\.[0-9]+\.[0-9]+\.[0-9]+:(?:[12456789]|3[123456790])"
]
They fix it

**Comment by Jo0kker** [comment]
Hello
Where put this ?
Th :)

**Comment by oscsystemx** [comment]
> Hello
> Where put this ?
> Th :)

no you dont have to do anything. Its works rn

**Comment by Jo0kker** [comment]
sorry i don't understand.
where your array go ?
in nui/script.js ?

**Comment by Jo0kker** [comment]
i change this  ?? 
`new WebSocket('ws://127.0.0.1:38204/tokovoip')`

**Comment by spoty123** [comment]
You don't have to change anything, it's fixed.

**Comment by Jo0kker** [comment]
OK think's :)

**Comment by swat30** [comment]
Where did this get fixed? I'm not seeing any changes to https://runtime.fivem.net/nui-blacklist.json or any recent TokoVoIP updates.

**Comment by spoty123** [comment]
I mean it works for me again, for now

**Comment by Harybo** [comment]
> Où cela a-t-il été résolu? Je ne vois aucune modification de https://runtime.fivem.net/nui-blacklist.json ou des mises à jour récentes de TokoVoIP.

relaunch fivem and have fun :)

**Comment by SilverNick** [comment]
it works for now but will not for long fivem has said to fix it

**Comment by Itokoyamato** [comment]
It does seem they have whitelisted it again, I'll try to look into a long term solution asap.

**Comment by swat30** [comment]
FYI we've implemented a workaround using users' hosts files to point a hostname to 127.0.0.1. This tricked FiveM into allowing the connection.

We're going to be keeping this workaround until a patch has been released to avoid further potential issues w/ FiveM changes.

**Comment by BadGirl7** [comment]
hello always this blocking of tokovoip. what to do?
![image](https://user-images.githubusercontent.com/62516086/77256065-28808300-6c6c-11ea-844d-f1d7061d9d67.png)

**Comment by dexlord30** [comment]
with latest update again tokovoip stays offline while im trying to join to server also it just happens to me in the server. what can i do ? please explain it like telling to idiot

**Comment by BadGirl7** [comment]
I solved the problem thank you

**Comment by dexlord30** [comment]
> I solved the problem thank you
can you explain how to do

**Comment by BadGirl7** [comment]
I just took the last nui / script file and replace mine and it works again

**Comment by dexlord30** [comment]
> I just took the last nui / script file and replace mine and it works again

where is the place for replace

**Comment by dexlord30** [comment]
> I just took the last nui / script file and replace mine and it works again

and which files exactly sorry for bothering you ım pretty new about those thing

**Comment by BadGirl7** [comment]
https://github.com/Itokoyamato/TokoVOIP_TS3/releases/download/v1.2.5-v1.3.5/tokovoip_script.zip

**Comment by dexlord30** [comment]
> https://github.com/Itokoyamato/TokoVOIP_TS3/releases/download/v1.2.5-v1.3.5/tokovoip_script.zip

ı just found it bu where should i replace it exactly

**Comment by BadGirl7** [comment]
File nui/ script replace this file

**Comment by dexlord30** [comment]
> File nui/ script replace this file

I'm really really sory ım really far away about those knowledges but I've downloaded it and ı have tokocoip_script file so now on the should i move it . like c/programfiles/teamspeak/plugins etc or something?
