### ISSUE TITLE
Tokovoip not working 

### ISSUE THREAD

**Issue by agplayswith** [Itokoyamato/TokoVOIP_TS3#90]
Hi, I have an issue. I can not connect to the specific fivem RP server. As you can see on the pic the TS3 has no error messages. I can connect to other server with tokiovoip but not for this. I did reinstall ts3, tokovoip but same issue. 
https://i.imgur.com/YXsbMOP.jpg

**Comment by LeandroTiim** [comment]
Were you able to solve this problem? I'm going through the same situation, please help me!

**Comment by llewys03** [comment]
Did you find a solution as i am having the same issue. help?

**Comment by Itokoyamato** [comment]
Check your firewall or antivirus to see if it could be blocking tokovoip.
Tokovoip 1.5.0 has been [released](https://github.com/itokoyamato/tokovoip_ts3/releases) and should be more stable
Please try again once your server is updated to tokovoip 1.5.0. (don't update your teamspeak plugin until the server you play on updates as well)
Feel free to open a new issue if the problem persists on the latest versions.
