### ISSUE TITLE
hear everyone

### ISSUE THREAD

**Issue by promraungdet** [Itokoyamato/TokoVOIP_TS3#92]
hear everyone after use onesync_enableInfinity 200 slot how to fix ?

**Comment by KewaiiGamer** [comment]
speak english much can you?

**Comment by promraungdet** [comment]
> speak english much can you?

im bad speak english

**Comment by Poggicek** [comment]
Tokovoip currently doesn't support onesync infinity. You have no way of fixing it expect for recoding the script. This can change anytime. < (19/4/2020).

**Comment by Itokoyamato** [comment]
Tokovoip 1.5.0 has been [released](https://github.com/itokoyamato/tokovoip_ts3/releases) and fully supports onesync infinity
Please try again once your server is updated to tokovoip 1.5.0. (don't update your teamspeak plugin until the server you play on updates as well)
Feel free to open a new issue if the problem persists on the latest versions.
