### ISSUE TITLE
Tokovoip problem

### ISSUE THREAD

**Issue by HamzaLCDP** [Itokoyamato/TokoVOIP_TS3#94]
I have a problem and i need a solution for it. I have been playing on a fivem server that needs tokovoip and teamspeak. At first it was working well. Then the problem started that i cant hear players near me but i hear players that are talking to each other and arent near me, like their on the other side of the map and i hear them. And Tokovoip keeps disconnecting.I deleted and reinstalled both of them but the problem stayed.
Please help because the problem is realy annoying.
Thanks. Best regards Hamza
![unknown](https://user-images.githubusercontent.com/63799016/79468253-fc53ea00-7ffe-11ea-951a-f33cf68ecbb1.png)

**Comment by Poggicek** [comment]
Give more info please.

How to reproduce it.
What are your server settings (normal onesync / bigmode)

Keep in mind developers have to reproduce things in order to fix them.

**Comment by HamzaLCDP** [comment]
> Give more info please.
> 
> How to reproduce it.
> What are your server settings (normal onesync / bigmode)
> 
> Keep in mind developers have to reproduce things in order to fix them.

like i said i keep hearing people that are not near me. I always should reload Tokovoip from teamspeak addons to hear people near me. but when i go away from those people i keep hearing them and i need to reload tokovoip one more time. Most times reloading tokovoip doesnt make a difference. People can hear me but i cant hear them.

**Comment by Itokoyamato** [comment]
Tokovoip 1.5.0 has been [released](https://github.com/itokoyamato/tokovoip_ts3/releases)
Please try again once your server is updated to tokovoip 1.5.0. (don't update your teamspeak plugin until the server you play on updates as well)
Feel free to open a new issue if the problem persists on the latest versions.
