### ISSUE TITLE
Toko voip crashing teamspek when launching

### ISSUE THREAD

**Issue by alficondo** [Itokoyamato/TokoVOIP_TS3#96]
for some reason it will crash after I install it and then launch teamspeak reinstalled 1000 times still the same error

**Comment by Poggicek** [comment]
no info

**Comment by alficondo** [comment]
how can I give you more info it just opens a crash log and sends a error to teamspeak? the only thing ive done Is delete the .dll file and then my teamspeak works again otherwise it wont open teamspeak

**Comment by alficondo** [comment]
Sent: 16384/61611 bytes
Sent: 61611/61611 bytes
Error: 201
AccessDeniedInvalid according to Policy: Policy expired.D8635E14DBB0E20DheJhKidJ67fp+e9u3AofXvpFAvDdU39i40ABwhq5Q+ibIgYgXtMNB5xX56RV5FTfshCwxeRKRJs=

**Comment by Itokoyamato** [comment]
Unfortunately, this is not a crash report. This is just teamspeak sending crash data, so it doesn't help.
Tokovoip 1.5.0 has been [released](https://github.com/itokoyamato/tokovoip_ts3/releases) and should be more stable
Please try again once your server is updated to tokovoip 1.5.0. (don't update your teamspeak plugin until the server you play on updates as well)
Feel free to open a new issue if the problem persists on the latest versions.
