### ISSUE TITLE
TeamSpeak crash when I use tokovoip

### ISSUE THREAD

**Issue by ITzPeppeh** [Itokoyamato/TokoVOIP_TS3#98]
Hi, sometimes my TeamSpeak 3 Client crashed. crash log:
```
Sent: 16384/252043 bytes
Sent: 131072/252043 bytes
Sent: 212992/252043 bytes
Sent: 252043/252043 bytes
Error: 201
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Invalid according to Policy: Policy expired.</Message><RequestId>02C04361AD84F9BC</RequestId><HostId>WDuZR8QyPaAlbWgLvyGDZGg2iyq/LGNU9H7G/XNBqajCUsf3eaPMoGI+0OmdJsYPWfmP64d0THw=</HostId></Error>
```

**Comment by alficondo** [comment]
how do I generate this crash log where can I find it

**Comment by ITzPeppeh** [comment]
After crash appears the crash log

**Comment by alficondo** [comment]
lemme check if I can copy it

**Comment by alficondo** [comment]
its just coming up blank ive had this problem for time bro

**Comment by alficondo** [comment]
Sent: 16384/61611 bytes
Sent: 61611/61611 bytes
Error: 201
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Invalid according to Policy: Policy expired.</Message><RequestId>D8635E14DBB0E20D</RequestId><HostId>heJhKidJ67fp+e9u3AofXvpFAvDdU39i40ABwhq5Q+ibIgYgXtMNB5xX56RV5FTfshCwxeRKRJs=</HostId></Error>

**Comment by alficondo** [comment]
its the same error bro

**Comment by Itokoyamato** [comment]
Unfortunately, this is not a crash report. This is just teamspeak sending crash data, so it doesn't help.
Tokovoip 1.5.0 has been [released](https://github.com/itokoyamato/tokovoip_ts3/releases) and should be more stable
Please try again once your server is updated to tokovoip 1.5.0. (don't update your teamspeak plugin until the server you play on updates as well)
Feel free to open a new issue if the problem persists on the latest versions.
