### ISSUE TITLE
Uninstalling TokoVOIP

### ISSUE THREAD

**Issue by Grey59x** [Itokoyamato/TokoVOIP_TS3#99]
Im having trouble removing this plugin completely. Even after uninstalling it from TeamSpeak, TokoVOIP still has the pop-up menu on other servers. I can't even play without this pop-up blocking my screen.

![toko](https://user-images.githubusercontent.com/64233927/80159671-39852280-8591-11ea-8a1d-e1a2bd74fd08.PNG)

**Comment by floppypancakes4u** [comment]
Uhhh... I can't tell if you are being serious or not.

The popup comes up on other servers cause they still use the resource on their servers. It will continue to show up until you re-install the plugin on TS.

**Comment by Grey59x** [comment]
Yeah.. realized that a couple hours ago. Thanks.
